### PR TITLE
WIP: Rel 20.17 03

### PR DESCRIPTION
**Pull request by nnshah1**
updating to public va serving repository

### CODE REVIEW

**Comment by xwu2git** [comment]
@nnshah1 , could you merge against the v20.4 branch instead? We cannot merge to master yet as base images are not available in dockerhub.

**Comment by nnshah1** [comment]
@xwu2git updated the target - let me know if that worked

**Comment by nnshah1** [comment]
Not sure exactly how this relates: but this is the pull request I changed:

https://github.com/OpenVisualCloud/Smart-City-Sample/pull/386

**Comment by nnshah1** [comment]
Covered here: #386

**Pull request closed without merging**
