### PR TITLE
5g camera gateway

### PR DESCRIPTION
**Pull request by QuPengfei**

### CODE REVIEW

**Comment by xwu2git** [comment]
- deployment/camera_gateway should be part of the helm deployment. The camera gateway isn't a complete deployment.  
- why edge gateway needs to proxy rtmp?

**Comment by QuPengfei** [comment]
There are two ways to deploy the camera gateway.  one way for helm is SCOPE=officex-camera make start_helm. the other way is  container-only.

For rtmp proxy, the initial idea is only to expose the rtmp/db service via the office gateway.  office gateway is the only interface or API gateway for external access.

**Comment by QuPengfei** [comment]
@xwu2git , update the patches, please review.

**Comment by xwu2git** [comment]
- I wonder if you really need the camera-gateway=enable setting on the analytics containers. Is it possible to deduce from the rtsp/rtmp URL prefix?   
- `helm/readme.md` not updated. Still show `make start_camera-gateway`.  Instead it should be `SCOPE=office1-camera make start_helm`   
- Why you need to update sensorinfo in sensorsdb? Why sensor_id is provided from external?    
- `db_init`: it's ok to over initialize. You probably don't need to set camera_gateway=enable. Office registration can be turned off if dbchost is none.  
- `discovery.py`: `camera_gateway` is equivalent to `rtmphost`. Overall, there are too many `camrea_gateway=enable`. Are they all necessary?  
- It might make sense to rename `sensor/streaming` to `sensor/rtmp`, to be consistent with `sensor/webrtc`.

**Comment by QuPengfei** [comment]
@xwu2git  update the patch accordingly. 
- remove the camrea_gateway=enable
- rename the streaming to rtmp
-  update the doc

Why you need to update sensorinfo in sensorsdb? Why sensor_id is provided from external?
> this keep the sync sensor db between camera gateway and office

**Pull request merged**
