### PR TITLE
GB28181 enable

### PR DESCRIPTION
**Pull request by QuPengfei**

### CODE REVIEW

**Review by xwu2git — COMMENTED** [review]
Can you reuse ffmpeg from one of the OVC software stacks?

**Comment by nnshah1** [comment]
@QuPengfei What's the goal here? I see we are adding back a local version of vaserving? (Is that correct or am I missing something)

I would definitely want to know the reason and avoid that if at all possible (want to keep it coming from a VA Serving tagged release)

**Comment by QuPengfei** [comment]
> Can you reuse ffmpeg from one of the OVC software stacks?

yes. update with openvisualcloud/xeon-centos7-media-ffmpeg

**Comment by QuPengfei** [comment]
> @QuPengfei What's the goal here? I see we are adding back a local version of vaserving? (Is that correct or am I missing something)
> 
> I would definitely want to know the reason and avoid that if at all possible (want to keep it coming from a VA Serving tagged release)

some user met the issue when building the image with vaserving from github.  so we keep it in local and avoid that. it does not occur for all the users.

**Comment by nnshah1** [comment]
> > @QuPengfei What's the goal here? I see we are adding back a local version of vaserving? (Is that correct or am I missing something)
> > I would definitely want to know the reason and avoid that if at all possible (want to keep it coming from a VA Serving tagged release)
> 
> some user met the issue when building the image with vaserving from github. so we keep it in local and avoid that. it does not occur for all the users.

Please provide more details - would like to fix the root cause. Making it local will be difficult to support / maintain -

**Comment by QuPengfei** [comment]
> > > @QuPengfei What's the goal here? I see we are adding back a local version of vaserving? (Is that correct or am I missing something)
> > > I would definitely want to know the reason and avoid that if at all possible (want to keep it coming from a VA Serving tagged release)
> > 
> > 
> > some user met the issue when building the image with vaserving from github. so we keep it in local and avoid that. it does not occur for all the users.
> 
> Please provide more details - would like to fix the root cause. Making it local will be difficult to support / maintain -

that is related to  network in PRC.  some user 's network are not reliable. that will cause the failure to fetch files.

**Comment by nnshah1** [comment]
> > > > @QuPengfei What's the goal here? I see we are adding back a local version of vaserving? (Is that correct or am I missing something)
> > > > I would definitely want to know the reason and avoid that if at all possible (want to keep it coming from a VA Serving tagged release)
> > > 
> > > 
> > > some user met the issue when building the image with vaserving from github. so we keep it in local and avoid that. it does not occur for all the users.
> > 
> > 
> > Please provide more details - would like to fix the root cause. Making it local will be difficult to support / maintain -
> 
> that is related to network in PRC. some user 's network are not reliable. that will cause the failure to fetch files.

@QuPengfei  Can you help us reproduce it?

I believe we can trim down so it is more repeatable and/or mirror to a PRC friendly github. How do you handle this for Smart Cities in general?

@whbruce

**Comment by xwu2git** [comment]
The big issue here is that wget sometimes does not return proper error code if a download is not complete, which causes all sorts of silent-failure strange behaviors. In unreliable network, this is 1 more thing we want to avoid. The alternative I can think of is to have the upstream targz the archive. Any corrupted download will fail the unzip process. Or we use md5sum, which is overkill.

**Comment by xwu2git** [comment]
@QuPengfei, can you decouple the vaserving piece with another commit? Let's get gb28181 in first.

**Comment by QuPengfei** [comment]
@nnshah1 @xwu2git  Now it is only GB28181 feature. will refine va service later.

**Review by xwu2git — APPROVED** [review]

**Comment by whbruce** [comment]
We have addressed similar PRC download issues for gstreamer images, but the same approach will work for ffmpeg. The following process should only result in one wget call - to download VA serving source code
1. Get VA Serving code from [release tarball](https://github.com/intel/video-analytics-serving/archive/v0.4.0-beta.tar.gz) instead of git
2. Use a pre-built base image. Release 0.4 uses openvisualcloud/xeone3-ubuntu1804-analytics-ffmpeg:20.10 by default

As our models are no longer checked in, the build process now downloads of the OpenVINO data_dev image for model conversion.

**Comment by QuPengfei** [comment]
> We have addressed similar PRC download issues for gstreamer images, but the same approach will work for ffmpeg. The following process should only result in one wget call - to download VA serving source code
> 
> 1. Get VA Serving code from [release tarball](https://github.com/intel/video-analytics-serving/archive/v0.4.0-beta.tar.gz) instead of git
> 2. Use a pre-built base image. Release 0.4 uses openvisualcloud/xeone3-ubuntu1804-analytics-ffmpeg:20.10 by default
> 
> As our models are no longer checked in, the build process now downloads of the OpenVINO data_dev image for model conversion.

will file a new PR about VA service

**Pull request merged**
