### PR TITLE
Smartstadium

### PR DESCRIPTION
**Pull request by yimm0815**

### CODE REVIEW

**Comment by xwu2git** [comment]
Try not to use pip at all time, unless equivalent apt-get cannot do. Pip will enlarge the deployment image unnecessarily by including the entire gcc tool chain.

**Comment by yimm0815** [comment]
Don’t see any better substitute. Do you have any idea?

**Comment by xwu2git** [comment]
Why? python3-pillow is readily available.

**Comment by yimm0815** [comment]
you are right. code checked in at https://github.com/OpenVisualCloud/Smart-City-Sample/pull/286.

**Pull request merged**
